services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  ts:
    context: ts
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  go:
    context: go
